name = "Stylecraft"
author = "AendrewHD"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "724092efc7af7965add184c4c6f4d9067b915fa4007d883eacf8f999bf5c2274"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
