name = "Stylecraft"
author = "AendrewHD"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b808f4a16f0d57f671cfbb35241a64039c254c8e5c25eaf098b57e9d29c730b5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
