name = "Stylecraft"
author = "AendrewHD"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3966bb444a6768eb84c1c394d915f93f9a47f9a35c17562e4720e7855b79c9dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
